### ISSUE TITLE
continuously test coala-emacs

### ISSUE THREAD

**Issue by fneu** [coala/coala-emacs#11]
There should be regular tests of coala-emacs to ensure flawless functionality with the latest versions of coala.

**Comment by fleimgruber** [comment]
I went ahead and added basic project management and testing in https://github.com/fleimgruber/coala-emacs/commit/f403ad6caffb30896dbed5e7a221e600496d8431, see also https://travis-ci.org/fleimgruber/coala-emacs/builds/238334937.  Will rebase and create PR after https://github.com/coala/coala-emacs/pull/16 is merged.
