### ISSUE TITLE
I am getting a Json error

### ISSUE THREAD

**Issue by justinjk007** [coala/coala-emacs#14]
`Error from syntax checker coala: JSON readtable error`

I have pip3, coala and flycheck-coala from source. On windows 10 and using Emacs 25.1.1.
I am getting the error when trying to edit a python file, nothing is linted. I am also getting that error when try to lint it from cmd. I have both python 2 and 3 installed.

**Comment by justinjk007** [comment]
Wait a minute, if I am getting the error on console, doesn't that mean the error is with coala itself, I will start an issue at Coala itslef

**Comment by Makman2** [comment]
how did you exactly invoke coala on the command line without emacs?

**Comment by justinjk007** [comment]
Oh, great. It worked now. Now that I am looking into it I named the file wrong and Also found out I have to make changes to my work environment. Thanks for asking the right question. We can close this issue I guess. It was my silly mistake.

**Comment by justinjk007** [comment]
I should ask a question, Does this mean I have to have a .coafile on every repo to integrate it with emacs

**Comment by Makman2** [comment]
yes, `coala` uses the `.coafile` in your repo to fetch the code rules / checks. `coala` can't (yet :D) predict completely what you want ;)

**Comment by justinjk007** [comment]
Thank you very much, may the linting begin...
