### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by co-robo** [coala/coala-emacs#21]
Add .editorconfig file for this repository.
Reference: http://editorconfig.org/
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=5a01685186d308b755b946eb)

**Comment by jayvdb** [comment]
https://gitlab.com/coala/mobans/issues/2

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6740451672457216](https://codein.withgoogle.com/dashboard/tasks/6740451672457216).
