### ISSUE TITLE
Fix Travis Build error

### ISSUE THREAD

**Issue by co-robo** [coala/coala-emacs#22]
Read Travis CI log and fix it.
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=5a0168a55a1758ed0f9a3f6a)

**Comment by jayvdb** [comment]
Please create good issues with links to travis logs, etc.

**Comment by aashutoshrathi** [comment]
Check Travis log here: https://travis-ci.org/coala/coala-emacs

**Comment by jayvdb** [comment]
that is not a good link.  precise links, with the relevant snippets copied here .

**Comment by 9r0x** [comment]
I am working on pr #20 and maybe I can fix it

**Comment by jayvdb** [comment]
https://travis-ci.org/coala/coala-emacs/builds/255744435 is a build that failed.
That was the push for https://github.com/coala/coala-emacs/pull/17 , which did pass during the PR

**Comment by 9r0x** [comment]
@jayvdb @aashutoshrathi Fixed now, it was a problem caused by upstream repo https://github.com/melpa/melpa/issues/3833

**Comment by jayvdb** [comment]
Thanks @Grox-Ni for investigating.
